# Generated by Django 4.1.6 on 2023-02-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="code",
            new_name="origin",
        ),
    ]
