# Generated by Django 4.1.6 on 2023-02-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_rename_code_flight_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passanger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=64)),
                ("last", models.CharField(max_length=64)),
                (
                    "flights",
                    models.ManyToManyField(
                        blank=True, related_name="passengers", to="flights.flight"
                    ),
                ),
            ],
        ),
    ]
