# Generated by Django 4.1.6 on 2023-02-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_passanger"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Passanger",
            new_name="Passenger",
        ),
    ]
